version: '3.8'

services:
  node_backend:
    container_name: express_api
    image: express-api-test0.0.5
    build:
      context: ./API
    ports: ["5000:5000"]
    environment:
      - EXTERNAL_PORT=5000
      - PGDATABASE=node_db
      - PGUSER=will
      - PGPASSWORD=12345
      - PGHOST=node_db
      - TOKEN_KEY=23492fj230fj40fe-f2jke-f9dj23q4-9tq3j4-f9jq3gjmq3egvmqe34-v9q3jk50f8jnq3490f[3qgo[0wn45v0w58hjg-4tq3]]
      - EXPIRE_TIME=1h
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=will
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=node_db
    volumes:
      - node_postgres_data:/var/lib/postgresql/data

volumes:
  node_postgres_data: {}
