version: '3.8'

services:
  node_backend:
    container_name: express_api
    image: express-api-test0.0.3
    build:
      context: .
    ports: ["5001:5001"]
    environment:
      - EXTERNAL_PORT=5001
      - PGDATABASE=node_db
      - PGUSER=will
      - PGPASSWORD=12345
      - PGHOST=node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=will
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=node_db
    volumes:
      - node_postgres_data:/var/lib/postgresql/data

volumes:
  node_postgres_data: {}